export const navLinks = [
  {
    name: "The League",
    links: [
      { title: "Teams", path: "/teams" },
      { title: "Fixtures", path: "/fixtures" },
      { title: "Results", path: "/results" },
      { title: "Hall of Fame", path: "/hall-of-fame" },
    ],
  },
  {
    name: "News & Media",
    links: [
      { title: "News", path: "/news" },
      { title: "Blog", path: "/blog" },
      { title: "Press Release", path: "/press-release" },
      { title: "Gallery", path: "/gallery" },
      { title: "Videos", path: "/videos" },
    ],
  },
  {
    name: "Partners",
    links: [
      { title: "Sponsors", path: "/sponsors" },
      { title: "Partner", path: "/partner" },
    ],
  },
  {
    name: "Store",
    links: [
      { title: "Kits", path: "/kits" },
      { title: "Equipment", path: "/equipment" },
      { title: "Wearables", path: "/wearables" },
    ],
  },
  {
    name: "More",
    links: [
      { title: "Volunteers", path: "/volunteers" },
      { title: "Unifest", path: "/unifest" },
      { title: "Masterclass", path: "/masterclass" },
      { title: "GameTime", path: "/gametime" },
    ],
  },
];

export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const product = {
  data: [
    {
      id: 1,
      Title: "UNIBEN Royals Home Authentic Shirt 2021",
      Slug: "uniben-royals-home-authentic-shirt-2021",
      Details:
        "<p>YOUR TEAM. YOUR COLOURS.</p><p>The UNIBEN Royals Home Authentic Shirt is the same one worn by the team on the pitch.</p><ul><li>Replica style – looser fit across the chest and shoulders with straight hemline</li><li>Fabric: 50% recycled polyester fabric</li><li>Machine wash</li></ul><p>Wear your shirt with pride and show your support for the Royals<br>Why not make it your own by having your chosen name and number printed on the back?</p>",
      ProductCode: "LK1090927",
      InStock: true,
      PreOrder: false,
      Price: 6000,
      DiscountPrice: 4500,
      createdAt: "2022-06-09T14:05:27.918Z",
      updatedAt: "2022-06-09T14:05:33.883Z",
      publishedAt: "2022-06-09T14:05:33.879Z",
      Category: "Kit",
      CoverImage: [
        {
          id: 9,
          name: "60b38318b8294.png",
          alternativeText: "60b38318b8294.png",
          caption: "60b38318b8294.png",
          width: 396,
          height: 396,
          formats: {
            thumbnail: {
              ext: ".png",
              url: "https://hifl-files.ams3.digitaloceanspaces.com/thumbnail_60b38318b8294_877081a256.png",
              hash: "thumbnail_60b38318b8294_877081a256",
              mime: "image/png",
              name: "thumbnail_60b38318b8294.png",
              path: null,
              size: 35.91,
              width: 156,
              height: 156,
            },
          },
          hash: "60b38318b8294_877081a256",
          ext: ".png",
          mime: "image/png",
          size: 38.15,
          url: "https://hifl-files.ams3.digitaloceanspaces.com/60b38318b8294_877081a256.png",
          previewUrl: null,
          provider: "aws-s3",
          provider_metadata: null,
          createdAt: "2022-06-09T14:04:47.271Z",
          updatedAt: "2022-06-09T14:04:47.271Z",
        },
      ],
      ProductGallery: [
        {
          id: 9,
          name: "60b38318b8294.png",
          alternativeText: "60b38318b8294.png",
          caption: "60b38318b8294.png",
          width: 396,
          height: 396,
          formats: {
            thumbnail: {
              ext: ".png",
              url: "https://hifl-files.ams3.digitaloceanspaces.com/thumbnail_60b38318b8294_877081a256.png",
              hash: "thumbnail_60b38318b8294_877081a256",
              mime: "image/png",
              name: "thumbnail_60b38318b8294.png",
              path: null,
              size: 35.91,
              width: 156,
              height: 156,
            },
          },
          hash: "60b38318b8294_877081a256",
          ext: ".png",
          mime: "image/png",
          size: 38.15,
          url: "https://hifl-files.ams3.digitaloceanspaces.com/60b38318b8294_877081a256.png",
          previewUrl: null,
          provider: "aws-s3",
          provider_metadata: null,
          createdAt: "2022-06-09T14:04:47.271Z",
          updatedAt: "2022-06-09T14:04:47.271Z",
        },
        {
          id: 7,
          name: "60b3833096e27.png",
          alternativeText: "60b3833096e27.png",
          caption: "60b3833096e27.png",
          width: 396,
          height: 396,
          formats: {
            thumbnail: {
              ext: ".png",
              url: "https://hifl-files.ams3.digitaloceanspaces.com/thumbnail_60b3833096e27_11db4bbff8.png",
              hash: "thumbnail_60b3833096e27_11db4bbff8",
              mime: "image/png",
              name: "thumbnail_60b3833096e27.png",
              path: null,
              size: 34,
              width: 156,
              height: 156,
            },
          },
          hash: "60b3833096e27_11db4bbff8",
          ext: ".png",
          mime: "image/png",
          size: 44.57,
          url: "https://hifl-files.ams3.digitaloceanspaces.com/60b3833096e27_11db4bbff8.png",
          previewUrl: null,
          provider: "aws-s3",
          provider_metadata: null,
          createdAt: "2022-06-09T14:04:45.380Z",
          updatedAt: "2022-06-09T14:04:45.380Z",
        },
        {
          id: 8,
          name: "60b38318b86e4.png",
          alternativeText: "60b38318b86e4.png",
          caption: "60b38318b86e4.png",
          width: 396,
          height: 396,
          formats: {
            thumbnail: {
              ext: ".png",
              url: "https://hifl-files.ams3.digitaloceanspaces.com/thumbnail_60b38318b86e4_bca027f4bc.png",
              hash: "thumbnail_60b38318b86e4_bca027f4bc",
              mime: "image/png",
              name: "thumbnail_60b38318b86e4.png",
              path: null,
              size: 23.32,
              width: 156,
              height: 156,
            },
          },
          hash: "60b38318b86e4_bca027f4bc",
          ext: ".png",
          mime: "image/png",
          size: 26.61,
          url: "https://hifl-files.ams3.digitaloceanspaces.com/60b38318b86e4_bca027f4bc.png",
          previewUrl: null,
          provider: "aws-s3",
          provider_metadata: null,
          createdAt: "2022-06-09T14:04:45.331Z",
          updatedAt: "2022-06-09T14:04:45.331Z",
        },
      ],
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 25,
      pageCount: 1,
      total: 1,
    },
  },
};
